import { Season } from '../app/features/details-seasons/interface/detailsSeason';

export const episodesSeason: Season = {
  _id: '5d753a082ea6b90010bff496',
  air_date: '2021-09-17',
  episodes: [
    {
      air_date: '2021-09-17',
      episode_number: 1,
      episode_type: 'standard',
      id: 1922715,
      name: 'Batatinha frita 1, 2, 3',
      overview:
        'Endividado, Gi-hun participa de um jogo misterioso na esperança de ganhar dinheiro fácil. Mas já na primeira rodada, uma verdadeira cena de horror acontece.',
      production_code: '',
      runtime: 61,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/vMFJS9LIUUAmQ1thq4vJ7iHKwRz.jpg',
      vote_average: 8.273,
      vote_count: 842,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: "Sang-woo's mother",
          credit_id: '614f3360c3514c002648f1d0',
          order: 18,
          adult: false,
          gender: 1,
          id: 1661283,
          known_for_department: 'Acting',
          name: '박혜진',
          original_name: '박혜진',
          popularity: 5.316,
          profile_path: '/5cM51cww0P6CVNCRt3BQrGERBfc.jpg',
        },
        {
          character: 'Racetrack man',
          credit_id: '614df771140bad0025384f67',
          order: 500,
          adult: false,
          gender: 2,
          id: 3207964,
          known_for_department: 'Acting',
          name: '김경민',
          original_name: '김경민',
          popularity: 1.8,
          profile_path: '/7d88xPM0traynfzvpqXo93SkYyP.jpg',
        },
        {
          character: "Gi-hoon's mother",
          credit_id: '614adf33b0422800438203b9',
          order: 501,
          adult: false,
          gender: 1,
          id: 141153,
          known_for_department: 'Acting',
          name: '김영옥',
          original_name: '김영옥',
          popularity: 10.739,
          profile_path: '/vBk5QGcAFl8rlbkOoV898pa5GAi.jpg',
        },
        {
          character: "Gi-hoon's friend",
          credit_id: '614f34d6aaf897008f208e81',
          order: 507,
          adult: false,
          gender: 2,
          id: 2204527,
          known_for_department: 'Acting',
          name: '이서환',
          original_name: '이서환',
          popularity: 14.27,
          profile_path: '/xy6JlnuWWtEgb4I6tPuTpYc7hxp.jpg',
        },
        {
          character: "Gi-hoon's ex-wife",
          credit_id: '614adf99c2823a006440b21b',
          order: 508,
          adult: false,
          gender: 1,
          id: 2256730,
          known_for_department: 'Acting',
          name: '강말금',
          original_name: '강말금',
          popularity: 12.036,
          profile_path: '/cSjcx2ZzjHNZMxj0b2buDi9PwTj.jpg',
        },
        {
          character: 'Seong Ga-yeong',
          credit_id: '614f356bb0460500285dec27',
          order: 509,
          adult: false,
          gender: 1,
          id: 3247184,
          known_for_department: 'Acting',
          name: 'Cho Ah-in',
          original_name: 'Cho Ah-in',
          popularity: 4.861,
          profile_path: '/AfjiXg5LliSk7OmCrNoHvltsmm.jpg',
        },
        {
          character: "'No. 369'",
          credit_id: '614f38d9e8a3e10043f93270',
          order: 510,
          adult: false,
          gender: 2,
          id: 1191708,
          known_for_department: 'Acting',
          name: '윤승훈',
          original_name: '윤승훈',
          popularity: 2.172,
          profile_path: '/1HJzE4uLVU89J2EbcTTQIkY5JS0.jpg',
        },
        {
          character: "'No. 118'",
          credit_id: '614fdf52aaf897004441da7b',
          order: 511,
          adult: false,
          gender: 2,
          id: 3247799,
          known_for_department: 'Acting',
          name: 'Hong Woo-jin',
          original_name: 'Hong Woo-jin',
          popularity: 6.376,
          profile_path: '/1pkj23NEQezpzvmVbdTUw8Z9i8C.jpg',
        },
        {
          character: "'No. 250'",
          credit_id: '6150637b72d85500633dc680',
          order: 530,
          adult: false,
          gender: 2,
          id: 3038411,
          known_for_department: 'Acting',
          name: 'Park Ji-hoon',
          original_name: 'Park Ji-hoon',
          popularity: 4.96,
          profile_path: '/a1lhJxxIBlJL7roIDY4dOEoRMML.jpg',
        },
        {
          character: "'No. 107'",
          credit_id: '6150645a72d85500438561c8',
          order: 531,
          adult: false,
          gender: 1,
          id: 3248179,
          known_for_department: 'Acting',
          name: 'Park Seon-a',
          original_name: 'Park Seon-a',
          popularity: 1.785,
          profile_path: '/54Ede6Y2ABu62w3p9DRWXkbP5uY.jpg',
        },
        {
          character: "'No. 119'",
          credit_id: '615065d31c635b008f780c62',
          order: 532,
          adult: false,
          gender: 2,
          id: 3248192,
          known_for_department: 'Acting',
          name: '윤돈선',
          original_name: '윤돈선',
          popularity: 1.896,
          profile_path: '/2L1SkLovPObWYTNW8FnUgPi8eUf.jpg',
        },
        {
          character: "'No. 322'",
          credit_id: '61500a85124c8d006244ad9e',
          order: 535,
          adult: false,
          gender: 2,
          id: 3247887,
          known_for_department: 'Acting',
          name: '임기홍',
          original_name: '임기홍',
          popularity: 13.619,
          profile_path: '/LUXNTfJCsY74BdXKALauITHJA4.jpg',
        },
        {
          character: "'No. 062'",
          credit_id: '640c973aa894d600b81d74f4',
          order: 538,
          adult: false,
          gender: 2,
          id: 3758320,
          known_for_department: 'Acting',
          name: 'Lee Doo-seok',
          original_name: 'Lee Doo-seok',
          popularity: 5.879,
          profile_path: '/cQD0FqioziCBJE7KZC3KGmrO6xg.jpg',
        },
        {
          character: 'Ha Sun-young',
          credit_id: '6466b0bdd18572010196d5e0',
          order: 539,
          adult: false,
          gender: 1,
          id: 4069542,
          known_for_department: 'Acting',
          name: 'Wie Ji-Yeon',
          original_name: 'Wie Ji-Yeon',
          popularity: 0.813,
          profile_path: '/vPlpiQmgKUSsZ96O4PSXXPW4zvQ.jpg',
        },
        {
          character: 'Cho Sang-woo [Young]',
          credit_id: '6466b199006b010189579195',
          order: 540,
          adult: false,
          gender: 2,
          id: 4069543,
          known_for_department: 'Acting',
          name: 'Park Si-won',
          original_name: 'Park Si-won',
          popularity: 0.6,
          profile_path: '/vlVOPsQBZFJ0o3Lw3CnUsWnNEbY.jpg',
        },
        {
          character: 'Seong Gi-hoon [Child]',
          credit_id: '6466b26ac3514c00e5dc36b8',
          order: 541,
          adult: false,
          gender: 2,
          id: 4069546,
          known_for_department: 'Acting',
          name: 'Kim Yeon-woong',
          original_name: 'Kim Yeon-woong',
          popularity: 0.879,
          profile_path: '/z8o1i2MaH9MHa9SGHQBvuUlDmM4.jpg',
        },
        {
          character: "'No. 324'",
          credit_id: '6519b60b74507d00c577b896',
          order: 556,
          adult: false,
          gender: 2,
          id: 4300690,
          known_for_department: 'Acting',
          name: '이한솔',
          original_name: '이한솔',
          popularity: 2.038,
          profile_path: '/7Y7fZru4944rwZA4V3C4JJ6Y6ud.jpg',
        },
        {
          character: 'The Recruiter',
          credit_id: '6571b2c7a22d3e00accf157b',
          order: 557,
          adult: false,
          gender: 2,
          id: 150903,
          known_for_department: 'Acting',
          name: 'Gong Yoo',
          original_name: '공유',
          popularity: 93.937,
          profile_path: '/ocGoFb6TrK3uWGXt4WnuibUG1vD.jpg',
        },
        {
          character: 'Kim Jeong-tae',
          credit_id: '676d4ed662ba310fc0128b25',
          order: 560,
          adult: false,
          gender: 2,
          id: 1489972,
          known_for_department: 'Acting',
          name: '김법래',
          original_name: '김법래',
          popularity: 10.529,
          profile_path: '/9ceWebylO0MZcX56nP62BuSEhws.jpg',
        },
      ],
    },
    {
      air_date: '2021-09-17',
      episode_number: 2,
      episode_type: 'standard',
      id: 3146767,
      name: 'Inferno',
      overview:
        'Dividido entre continuar ou desistir, o grupo faz uma votação. Mas a realidade que enfrentam no mundo exterior pode ser tão impiedosa quanto o jogo.',
      production_code: '',
      runtime: 63,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/uacNwki3PqXEFk9Pal9Ng5NwwAI.jpg',
      vote_average: 8.154,
      vote_count: 227,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: "Sang-woo's mother",
          credit_id: '614f3360c3514c002648f1d0',
          order: 18,
          adult: false,
          gender: 1,
          id: 1661283,
          known_for_department: 'Acting',
          name: '박혜진',
          original_name: '박혜진',
          popularity: 5.316,
          profile_path: '/5cM51cww0P6CVNCRt3BQrGERBfc.jpg',
        },
        {
          character: "Gi-hoon's mother",
          credit_id: '614adf33b0422800438203b9',
          order: 501,
          adult: false,
          gender: 1,
          id: 141153,
          known_for_department: 'Acting',
          name: '김영옥',
          original_name: '김영옥',
          popularity: 10.739,
          profile_path: '/vBk5QGcAFl8rlbkOoV898pa5GAi.jpg',
        },
        {
          character: 'Dorm owner',
          credit_id: '614f3179fb8346006121c8cd',
          order: 503,
          adult: false,
          gender: 1,
          id: 3247167,
          known_for_department: 'Acting',
          name: 'Kim Gye-sun',
          original_name: 'Kim Gye-sun',
          popularity: 0.972,
          profile_path: '/t8FFgclT121W5srWX2jYVxye7jF.jpg',
        },
        {
          character: 'Kim Jin-woo (Police 2)',
          credit_id: '614f324cfb8346002c421467',
          order: 504,
          adult: false,
          gender: 2,
          id: 2854670,
          known_for_department: 'Acting',
          name: 'Kim Min-sik',
          original_name: 'Kim Min-sik',
          popularity: 3.615,
          profile_path: '/ldc5Z7dm7F71OhUoQ6wSx5SNyDQ.jpg',
        },
        {
          character: 'Kim Sang-hyuk (Police 1)',
          credit_id: '614f32db67203d0043f01f5e',
          order: 505,
          adult: false,
          gender: 2,
          id: 2159392,
          known_for_department: 'Acting',
          name: '이동용',
          original_name: '이동용',
          popularity: 2.958,
          profile_path: '/91FB6jpqgH6kcWb0PARCXswCidm.jpg',
        },
        {
          character: "Ali's wife",
          credit_id: '614f34b22d8ef300626a5c48',
          order: 506,
          adult: false,
          gender: 0,
          id: 3247183,
          known_for_department: 'Acting',
          name: 'Anwesha Purkayastha',
          original_name: 'Anwesha Purkayastha',
          popularity: 0.591,
          profile_path: '/kStrcO6wCyp9Im2hEt2srNgeqER.jpg',
        },
        {
          character: "Gi-hoon's friend",
          credit_id: '614f34d6aaf897008f208e81',
          order: 507,
          adult: false,
          gender: 2,
          id: 2204527,
          known_for_department: 'Acting',
          name: '이서환',
          original_name: '이서환',
          popularity: 14.27,
          profile_path: '/xy6JlnuWWtEgb4I6tPuTpYc7hxp.jpg',
        },
        {
          character: "Gi-hoon's ex-wife",
          credit_id: '614adf99c2823a006440b21b',
          order: 508,
          adult: false,
          gender: 1,
          id: 2256730,
          known_for_department: 'Acting',
          name: '강말금',
          original_name: '강말금',
          popularity: 12.036,
          profile_path: '/cSjcx2ZzjHNZMxj0b2buDi9PwTj.jpg',
        },
        {
          character: 'Seong Ga-yeong',
          credit_id: '614f356bb0460500285dec27',
          order: 509,
          adult: false,
          gender: 1,
          id: 3247184,
          known_for_department: 'Acting',
          name: 'Cho Ah-in',
          original_name: 'Cho Ah-in',
          popularity: 4.861,
          profile_path: '/AfjiXg5LliSk7OmCrNoHvltsmm.jpg',
        },
        {
          character: "'No. 369'",
          credit_id: '614f38d9e8a3e10043f93270',
          order: 510,
          adult: false,
          gender: 2,
          id: 1191708,
          known_for_department: 'Acting',
          name: '윤승훈',
          original_name: '윤승훈',
          popularity: 2.172,
          profile_path: '/1HJzE4uLVU89J2EbcTTQIkY5JS0.jpg',
        },
        {
          character: "'No. 453'",
          credit_id: '615003e1e8a3e10062184148',
          order: 521,
          adult: false,
          gender: 1,
          id: 3247875,
          known_for_department: 'Acting',
          name: '양말복',
          original_name: '양말복',
          popularity: 28.258,
          profile_path: '/mMfhiP92DDBPVs1OfzhcHE9lkvc.jpg',
        },
        {
          character: "Sae-byeok's brother",
          credit_id: '61502340a5d849008df7a3cd',
          order: 528,
          adult: false,
          gender: 2,
          id: 2053103,
          known_for_department: 'Acting',
          name: 'Park Si-wan',
          original_name: 'Park Si-wan',
          popularity: 5.598,
          profile_path: '/7M0Oo7oZOmlYeNelNsP0fy5CCUx.jpg',
        },
        {
          character: "'No. 322'",
          credit_id: '61500a85124c8d006244ad9e',
          order: 535,
          adult: false,
          gender: 2,
          id: 3247887,
          known_for_department: 'Acting',
          name: '임기홍',
          original_name: '임기홍',
          popularity: 13.619,
          profile_path: '/LUXNTfJCsY74BdXKALauITHJA4.jpg',
        },
        {
          character: "'No. 271'",
          credit_id: '63d27a45cb71b800d43a3968',
          order: 537,
          adult: false,
          gender: 2,
          id: 3837245,
          known_for_department: 'Acting',
          name: 'Min Tae-yul',
          original_name: 'Min Tae-yul',
          popularity: 1.828,
          profile_path: '/6CHwrivGdVqJQ2oXXUwPzXc1Z40.jpg',
        },
        {
          character: "'No. 028'",
          credit_id: '6466b4baa5046e01474bedf8',
          order: 542,
          adult: false,
          gender: 2,
          id: 1332468,
          known_for_department: 'Acting',
          name: '허동원',
          original_name: '허동원',
          popularity: 10.755,
          profile_path: '/2ozJdoP76fZvlLo1MhqPunoy6CW.jpg',
        },
        {
          character: 'Yoon [Emergency Medical Center doctor]',
          credit_id: '6466b5e2006b010126f4e3dc',
          order: 543,
          adult: false,
          gender: 2,
          id: 3768083,
          known_for_department: 'Acting',
          name: 'Song Hyeong-su',
          original_name: 'Song Hyeong-su',
          popularity: 0.988,
          profile_path: '/ixONpSmzDSycpB8y66QEjXyOkNn.jpg',
        },
        {
          character: 'Detective',
          credit_id: '6466b60d33a376011ec2cd49',
          order: 544,
          adult: false,
          gender: 2,
          id: 2144719,
          known_for_department: 'Acting',
          name: 'Kim Sung-gon',
          original_name: 'Kim Sung-gon',
          popularity: 0.534,
          profile_path: '/2vefWBAPBUW8pGagQb9h4OSLS7f.jpg',
        },
        {
          character: 'Detective',
          credit_id: '6466b623006b010189579292',
          order: 545,
          adult: false,
          gender: 2,
          id: 4010798,
          known_for_department: 'Acting',
          name: '소윤호',
          original_name: '소윤호',
          popularity: 1.555,
          profile_path: '/2P2kbbw3q2fwVx6ZyVzwwKccpdA.jpg',
        },
        {
          character: 'Gang member',
          credit_id: '6466b6f52bcf67011bf216d5',
          order: 546,
          adult: false,
          gender: 2,
          id: 3496489,
          known_for_department: 'Acting',
          name: '이충구',
          original_name: '이충구',
          popularity: 1.102,
          profile_path: '/xb9t22XXZijHqADsGU9lllfB1n.jpg',
        },
        {
          character: 'Factory owner',
          credit_id: '6466b771006b01010589206b',
          order: 547,
          adult: false,
          gender: 2,
          id: 4069568,
          known_for_department: 'Acting',
          name: 'Kim Seo-ha',
          original_name: 'Kim Seo-ha',
          popularity: 0.591,
          profile_path: '/pCZLJwC9BnYbTHLoSzCwpjeHlGj.jpg',
        },
        {
          character: "Ga-yeong's brother",
          credit_id: '6466b7f8d1857201402fc9dd',
          order: 548,
          adult: false,
          gender: 2,
          id: 4047048,
          known_for_department: 'Acting',
          name: 'Pyo Dong-jun',
          original_name: 'Pyo Dong-jun',
          popularity: 0.761,
          profile_path: '/1R0bKFQxaJHkgBjZFcOpri84tt9.jpg',
        },
        {
          character: 'Fish shop customer',
          credit_id: '6466b88fd18572010196d839',
          order: 549,
          adult: false,
          gender: 1,
          id: 3545970,
          known_for_department: 'Acting',
          name: 'Jeon Hyun-suk',
          original_name: 'Jeon Hyun-suk',
          popularity: 0.055,
          profile_path: '/iaWp17QwZbXzl4GPfoBC3Jrf44p.jpg',
        },
        {
          character: "Ga-yeong's stepfather",
          credit_id: '6466b8c033a376011ec2ce08',
          order: 550,
          adult: false,
          gender: 2,
          id: 3045793,
          known_for_department: 'Acting',
          name: '장재권',
          original_name: '장재권',
          popularity: 1.376,
          profile_path: '/kM22cXYreFyeaRR5DAakgRgkisr.jpg',
        },
        {
          character: "Gi-hoon's friend's wife",
          credit_id: '6466b97733a3760158d8aad4',
          order: 551,
          adult: false,
          gender: 1,
          id: 147853,
          known_for_department: 'Acting',
          name: '김영선',
          original_name: '김영선',
          popularity: 4.215,
          profile_path: '/iXAsncrUmI183e6osPzHxV6tNh4.jpg',
        },
        {
          character: 'North Korean defector shelter employee',
          credit_id: '6466b9df2bcf67013893909b',
          order: 552,
          adult: false,
          gender: 2,
          id: 572173,
          known_for_department: 'Acting',
          name: '최재섭',
          original_name: '최재섭',
          popularity: 1.579,
          profile_path: '/AblXBoGtLVLCiKIDvt175DMdk6d.jpg',
        },
      ],
    },
    {
      air_date: '2021-09-17',
      episode_number: 3,
      episode_type: 'standard',
      id: 3146768,
      name: 'O homem do guarda-chuva',
      overview:
        'Alguns jogadores entram na próxima rodada, que promete altos e baixos, além de vantagens ocultas. Jun-ho chega sorrateiramente.',
      production_code: '',
      runtime: 55,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/xNtgrNEsMXvmRQQtcFuJdbXOjmP.jpg',
      vote_average: 8.395,
      vote_count: 152,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: "'No. 111'",
          credit_id: '614df8b2124c8d0043b39641',
          order: 502,
          adult: false,
          gender: 2,
          id: 2221392,
          known_for_department: 'Acting',
          name: '유성주',
          original_name: '유성주',
          popularity: 9.693,
          profile_path: '/oPnBSNDIKvRTp312cBiMHxq6xOG.jpg',
        },
        {
          character: "'No. 369'",
          credit_id: '614f38d9e8a3e10043f93270',
          order: 510,
          adult: false,
          gender: 2,
          id: 1191708,
          known_for_department: 'Acting',
          name: '윤승훈',
          original_name: '윤승훈',
          popularity: 2.172,
          profile_path: '/1HJzE4uLVU89J2EbcTTQIkY5JS0.jpg',
        },
        {
          character: "'No. 278'",
          credit_id: '614fde69b04605008999f4e6',
          order: 515,
          adult: false,
          gender: 2,
          id: 1346900,
          known_for_department: 'Acting',
          name: '곽자형',
          original_name: '곽자형',
          popularity: 4.131,
          profile_path: '/tUUOHZmzyZFh7Jsj5yoWHYdRt47.jpg',
        },
        {
          character: "'No. 119'",
          credit_id: '615065d31c635b008f780c62',
          order: 532,
          adult: false,
          gender: 2,
          id: 3248192,
          known_for_department: 'Acting',
          name: '윤돈선',
          original_name: '윤돈선',
          popularity: 1.896,
          profile_path: '/2L1SkLovPObWYTNW8FnUgPi8eUf.jpg',
        },
        {
          character: '□ Mask',
          credit_id: '6166fd4781c7be0065e47245',
          order: 534,
          adult: false,
          gender: 2,
          id: 3267278,
          known_for_department: 'Acting',
          name: 'Lee Jung-jun',
          original_name: 'Lee Jung-jun',
          popularity: 4.525,
          profile_path: '/6s6dcghCl8rjvJ1TzxQt58fH9GV.jpg',
        },
        {
          character: "'No. 028'",
          credit_id: '6466b4baa5046e01474bedf8',
          order: 542,
          adult: false,
          gender: 2,
          id: 1332468,
          known_for_department: 'Acting',
          name: '허동원',
          original_name: '허동원',
          popularity: 10.755,
          profile_path: '/2ozJdoP76fZvlLo1MhqPunoy6CW.jpg',
        },
      ],
    },
    {
      air_date: '2021-09-17',
      episode_number: 4,
      episode_type: 'standard',
      id: 3146770,
      name: 'Fiquem juntos',
      overview:
        'Com alianças se formando entre os jogadores, ninguém está a salvo quando as luzes se apagam. O terceiro jogo desafia a equipe de Gi-hun a pensar estrategicamente.',
      production_code: '',
      runtime: 55,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/9cUGOdLN4gmnf3b9ILArnJsJI8Q.jpg',
      vote_average: 8.469,
      vote_count: 147,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: "'No. 111'",
          credit_id: '614df8b2124c8d0043b39641',
          order: 502,
          adult: false,
          gender: 2,
          id: 2221392,
          known_for_department: 'Acting',
          name: '유성주',
          original_name: '유성주',
          popularity: 9.693,
          profile_path: '/oPnBSNDIKvRTp312cBiMHxq6xOG.jpg',
        },
        {
          character: "'No. 194'",
          credit_id: '614fe3562f8d09006125d259',
          order: 512,
          adult: false,
          gender: 2,
          id: 3247803,
          known_for_department: 'Acting',
          name: 'Woo Young-taek',
          original_name: 'Woo Young-taek',
          popularity: 0.695,
          profile_path: '/gkfVEx78GLgyqUibTEfJkmkjMBL.jpg',
        },
        {
          character: "'No. 278'",
          credit_id: '614fde69b04605008999f4e6',
          order: 515,
          adult: false,
          gender: 2,
          id: 1346900,
          known_for_department: 'Acting',
          name: '곽자형',
          original_name: '곽자형',
          popularity: 4.131,
          profile_path: '/tUUOHZmzyZFh7Jsj5yoWHYdRt47.jpg',
        },
        {
          character: "'No. 070'",
          credit_id: '614df803b0460500447f0039',
          order: 516,
          adult: false,
          gender: 1,
          id: 1169315,
          known_for_department: 'Acting',
          name: '이지하',
          original_name: '이지하',
          popularity: 13.357,
          profile_path: '/5y307AdDZtZNeyshQEgvGieRmpy.jpg',
        },
        {
          character: "'No. 244'",
          credit_id: '614ff4d872d85500633d23ec',
          order: 518,
          adult: false,
          gender: 2,
          id: 2097079,
          known_for_department: 'Acting',
          name: '김서현',
          original_name: '김서현',
          popularity: 3.066,
          profile_path: '/AaXh6Ypbgiue2XcywEZurVFsB2c.jpg',
        },
        {
          character: "'No. 069'",
          credit_id: '614fd973c3514c00264aa15d',
          order: 520,
          adult: false,
          gender: 2,
          id: 88290,
          known_for_department: 'Acting',
          name: '김윤태',
          original_name: '김윤태',
          popularity: 2.451,
          profile_path: '/tTGfLo6DBo1eBEFMFWDQ90V25Gl.jpg',
        },
        {
          character: "'No. 196'",
          credit_id: '6150628b67dcc90062d613cd',
          order: 529,
          adult: false,
          gender: 2,
          id: 2471960,
          known_for_department: 'Acting',
          name: 'Kim Dong-hyun',
          original_name: 'Kim Dong-hyun',
          popularity: 1.572,
          profile_path: '/xBHBUMc4fWD8D1rirqIbTewSKGs.jpg',
        },
        {
          character: "'No. 271'",
          credit_id: '63d27a45cb71b800d43a3968',
          order: 537,
          adult: false,
          gender: 2,
          id: 3837245,
          known_for_department: 'Acting',
          name: 'Min Tae-yul',
          original_name: 'Min Tae-yul',
          popularity: 1.828,
          profile_path: '/6CHwrivGdVqJQ2oXXUwPzXc1Z40.jpg',
        },
        {
          character: "'No. 028'",
          credit_id: '6466b4baa5046e01474bedf8',
          order: 542,
          adult: false,
          gender: 2,
          id: 1332468,
          known_for_department: 'Acting',
          name: '허동원',
          original_name: '허동원',
          popularity: 10.755,
          profile_path: '/2ozJdoP76fZvlLo1MhqPunoy6CW.jpg',
        },
        {
          character: "'No. 276'",
          credit_id: '6466bc60d18572016190761d',
          order: 553,
          adult: false,
          gender: 2,
          id: 4069608,
          known_for_department: 'Acting',
          name: 'Chris Chan',
          original_name: 'Chris Chan',
          popularity: 1.041,
          profile_path: '/ajMIB02JTKGIVWTjWvNZOSs3XSo.jpg',
        },
      ],
    },
    {
      air_date: '2021-09-17',
      episode_number: 5,
      episode_type: 'standard',
      id: 3146771,
      name: 'Um mundo justo',
      overview:
        'Gi-hun e a equipe se revezam para vigiar durante a noite. Os homens mascarados enfrentam problemas inesperados.',
      production_code: '',
      runtime: 52,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/2pE9f6drlF7y9rwUw6dh1w6jF5M.jpg',
      vote_average: 8.024,
      vote_count: 125,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: "'No. 111'",
          credit_id: '614df8b2124c8d0043b39641',
          order: 502,
          adult: false,
          gender: 2,
          id: 2221392,
          known_for_department: 'Acting',
          name: '유성주',
          original_name: '유성주',
          popularity: 9.693,
          profile_path: '/oPnBSNDIKvRTp312cBiMHxq6xOG.jpg',
        },
        {
          character: "'No. 194'",
          credit_id: '614fe3562f8d09006125d259',
          order: 512,
          adult: false,
          gender: 2,
          id: 3247803,
          known_for_department: 'Acting',
          name: 'Woo Young-taek',
          original_name: 'Woo Young-taek',
          popularity: 0.695,
          profile_path: '/gkfVEx78GLgyqUibTEfJkmkjMBL.jpg',
        },
        {
          character: '○ Mask',
          credit_id: '614ff0322d8ef300421c485a',
          order: 513,
          adult: false,
          gender: 2,
          id: 1332468,
          known_for_department: 'Acting',
          name: '허동원',
          original_name: '허동원',
          popularity: 10.755,
          profile_path: '/2ozJdoP76fZvlLo1MhqPunoy6CW.jpg',
        },
        {
          character: '△ Mask / Surgery Room Guard 2',
          credit_id: '614ff15b158c850061ba0e02',
          order: 514,
          adult: false,
          gender: 2,
          id: 3247828,
          known_for_department: 'Acting',
          name: '윤주만',
          original_name: '윤주만',
          popularity: 3.578,
          profile_path: '/w6SCHHQa7ZpXkm2C4MVoLNbAHwE.jpg',
        },
        {
          character: "'No. 278'",
          credit_id: '614fde69b04605008999f4e6',
          order: 515,
          adult: false,
          gender: 2,
          id: 1346900,
          known_for_department: 'Acting',
          name: '곽자형',
          original_name: '곽자형',
          popularity: 4.131,
          profile_path: '/tUUOHZmzyZFh7Jsj5yoWHYdRt47.jpg',
        },
        {
          character: "'No. 244'",
          credit_id: '614ff4d872d85500633d23ec',
          order: 518,
          adult: false,
          gender: 2,
          id: 2097079,
          known_for_department: 'Acting',
          name: '김서현',
          original_name: '김서현',
          popularity: 3.066,
          profile_path: '/AaXh6Ypbgiue2XcywEZurVFsB2c.jpg',
        },
        {
          character: "'No. 196'",
          credit_id: '6150628b67dcc90062d613cd',
          order: 529,
          adult: false,
          gender: 2,
          id: 2471960,
          known_for_department: 'Acting',
          name: 'Kim Dong-hyun',
          original_name: 'Kim Dong-hyun',
          popularity: 1.572,
          profile_path: '/xBHBUMc4fWD8D1rirqIbTewSKGs.jpg',
        },
        {
          character: "'No. 021'",
          credit_id: '61659e90cee4810062ebc165',
          order: 533,
          adult: false,
          gender: 2,
          id: 3268405,
          known_for_department: 'Acting',
          name: '문병주',
          original_name: '문병주',
          popularity: 2.09,
          profile_path: null,
        },
        {
          character: 'Surgery Room Guard',
          credit_id: '616ee0e6a097dc002a92f190',
          order: 536,
          adult: false,
          gender: 2,
          id: 2240065,
          known_for_department: 'Acting',
          name: 'Yun Yeong-keol',
          original_name: 'Yun Yeong-keol',
          popularity: 0.917,
          profile_path: '/ooknKOjgXLEwZLxztJpANKVM3bB.jpg',
        },
      ],
    },
    {
      air_date: '2021-09-17',
      episode_number: 6,
      episode_type: 'standard',
      id: 3146772,
      name: 'Gganbu',
      overview:
        'Os jogadores formam duplas para o quarto jogo. Gi-hun enfrenta um dilema moral, Sang-woo escolhe se proteger e Sae-byeok conta sua história.',
      production_code: '',
      runtime: 62,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/cohCCQzTe2ncdQczJDUsO0vzxPR.jpg',
      vote_average: 8.858,
      vote_count: 120,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: "'No. 278'",
          credit_id: '614fde69b04605008999f4e6',
          order: 515,
          adult: false,
          gender: 2,
          id: 1346900,
          known_for_department: 'Acting',
          name: '곽자형',
          original_name: '곽자형',
          popularity: 4.131,
          profile_path: '/tUUOHZmzyZFh7Jsj5yoWHYdRt47.jpg',
        },
        {
          character: "'No. 070'",
          credit_id: '614df803b0460500447f0039',
          order: 516,
          adult: false,
          gender: 1,
          id: 1169315,
          known_for_department: 'Acting',
          name: '이지하',
          original_name: '이지하',
          popularity: 13.357,
          profile_path: '/5y307AdDZtZNeyshQEgvGieRmpy.jpg',
        },
        {
          character: "'No. 017'",
          credit_id: '614fe4b8158c850061b9ec00',
          order: 517,
          adult: false,
          gender: 2,
          id: 564847,
          known_for_department: 'Acting',
          name: '이상희',
          original_name: '이상희',
          popularity: 1.757,
          profile_path: '/wOYFSg20yGe48VFALqGAlrLjFHV.jpg',
        },
        {
          character: "'No. 244'",
          credit_id: '614ff4d872d85500633d23ec',
          order: 518,
          adult: false,
          gender: 2,
          id: 2097079,
          known_for_department: 'Acting',
          name: '김서현',
          original_name: '김서현',
          popularity: 3.066,
          profile_path: '/AaXh6Ypbgiue2XcywEZurVFsB2c.jpg',
        },
        {
          character: "'No. 069'",
          credit_id: '614fd973c3514c00264aa15d',
          order: 520,
          adult: false,
          gender: 2,
          id: 88290,
          known_for_department: 'Acting',
          name: '김윤태',
          original_name: '김윤태',
          popularity: 2.451,
          profile_path: '/tTGfLo6DBo1eBEFMFWDQ90V25Gl.jpg',
        },
        {
          character: "'No. 196'",
          credit_id: '6150628b67dcc90062d613cd',
          order: 529,
          adult: false,
          gender: 2,
          id: 2471960,
          known_for_department: 'Acting',
          name: 'Kim Dong-hyun',
          original_name: 'Kim Dong-hyun',
          popularity: 1.572,
          profile_path: '/xBHBUMc4fWD8D1rirqIbTewSKGs.jpg',
        },
        {
          character: "'No. 021'",
          credit_id: '61659e90cee4810062ebc165',
          order: 533,
          adult: false,
          gender: 2,
          id: 3268405,
          known_for_department: 'Acting',
          name: '문병주',
          original_name: '문병주',
          popularity: 2.09,
          profile_path: null,
        },
        {
          character: "'No. 062'",
          credit_id: '640c973aa894d600b81d74f4',
          order: 538,
          adult: false,
          gender: 2,
          id: 3758320,
          known_for_department: 'Acting',
          name: 'Lee Doo-seok',
          original_name: 'Lee Doo-seok',
          popularity: 5.879,
          profile_path: '/cQD0FqioziCBJE7KZC3KGmrO6xg.jpg',
        },
      ],
    },
    {
      air_date: '2021-09-17',
      episode_number: 7,
      episode_type: 'standard',
      id: 3146773,
      name: 'VIPs',
      overview:
        'O líder mascarado dá as boas-vindas aos convidados VIP que vão assistir ao show na primeira fileira. No quinto jogo, alguns jogadores cedem à pressão.',
      production_code: '',
      runtime: 58,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/4pVfv4HaM5QpFJTHm19p2UI0StN.jpg',
      vote_average: 8.214,
      vote_count: 112,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: "'No. 017'",
          credit_id: '614fe4b8158c850061b9ec00',
          order: 517,
          adult: false,
          gender: 2,
          id: 564847,
          known_for_department: 'Acting',
          name: '이상희',
          original_name: '이상희',
          popularity: 1.757,
          profile_path: '/wOYFSg20yGe48VFALqGAlrLjFHV.jpg',
        },
        {
          character: "'No. 244'",
          credit_id: '614ff4d872d85500633d23ec',
          order: 518,
          adult: false,
          gender: 2,
          id: 2097079,
          known_for_department: 'Acting',
          name: '김서현',
          original_name: '김서현',
          popularity: 3.066,
          profile_path: '/AaXh6Ypbgiue2XcywEZurVFsB2c.jpg',
        },
        {
          character: "'No. 308'",
          credit_id: '61500316af95900026fe1c86',
          order: 519,
          adult: false,
          gender: 1,
          id: 2759502,
          known_for_department: 'Acting',
          name: '황연희',
          original_name: '황연희',
          popularity: 0.926,
          profile_path: '/2PFZ14YwnAtFiWPRFw6n3svFRdJ.jpg',
        },
        {
          character: "'No. 069'",
          credit_id: '614fd973c3514c00264aa15d',
          order: 520,
          adult: false,
          gender: 2,
          id: 88290,
          known_for_department: 'Acting',
          name: '김윤태',
          original_name: '김윤태',
          popularity: 2.451,
          profile_path: '/tTGfLo6DBo1eBEFMFWDQ90V25Gl.jpg',
        },
        {
          character: "'No. 453'",
          credit_id: '615003e1e8a3e10062184148',
          order: 521,
          adult: false,
          gender: 1,
          id: 3247875,
          known_for_department: 'Acting',
          name: '양말복',
          original_name: '양말복',
          popularity: 28.258,
          profile_path: '/mMfhiP92DDBPVs1OfzhcHE9lkvc.jpg',
        },
        {
          character: "'No. 096'",
          credit_id: '6150074ac3514c00436d260e',
          order: 522,
          adult: false,
          gender: 2,
          id: 560068,
          known_for_department: 'Acting',
          name: '정우혁',
          original_name: '정우혁',
          popularity: 1.922,
          profile_path: '/ncYoJ3Ogxzz1h1Ps1YVSSErLXkb.jpg',
        },
        {
          character: 'VIP 4',
          credit_id: '614df541fb8346004333d34a',
          order: 523,
          adult: false,
          gender: 2,
          id: 94381,
          known_for_department: 'Acting',
          name: 'Geoffrey Giuliano',
          original_name: 'Geoffrey Giuliano',
          popularity: 13.51,
          profile_path: '/7qHL8KoQkJXtesvmB4mYITh71p2.jpg',
        },
        {
          character: 'VIP 2',
          credit_id: '614df623fb834600611f86bb',
          order: 524,
          adult: false,
          gender: 2,
          id: 3246187,
          known_for_department: 'Acting',
          name: 'Daniel C. Kennedy',
          original_name: 'Daniel C. Kennedy',
          popularity: 23.504,
          profile_path: '/xbLvXLtFZgoxiP6C7k6yB5IWVdk.jpg',
        },
        {
          character: 'VIP 1',
          credit_id: '614df72f2d8ef3002a96fed6',
          order: 525,
          adult: false,
          gender: 2,
          id: 2965857,
          known_for_department: 'Acting',
          name: 'John D. Michaels',
          original_name: 'John D. Michaels',
          popularity: 15.441,
          profile_path: '/1qFYRTG47z6Orgot2G9CcEwL86I.jpg',
        },
        {
          character: "'No. 021'",
          credit_id: '61659e90cee4810062ebc165',
          order: 533,
          adult: false,
          gender: 2,
          id: 3268405,
          known_for_department: 'Acting',
          name: '문병주',
          original_name: '문병주',
          popularity: 2.09,
          profile_path: null,
        },
        {
          character: "'No. 322'",
          credit_id: '61500a85124c8d006244ad9e',
          order: 535,
          adult: false,
          gender: 2,
          id: 3247887,
          known_for_department: 'Acting',
          name: '임기홍',
          original_name: '임기홍',
          popularity: 13.619,
          profile_path: '/LUXNTfJCsY74BdXKALauITHJA4.jpg',
        },
        {
          character: "'No. 062'",
          credit_id: '640c973aa894d600b81d74f4',
          order: 538,
          adult: false,
          gender: 2,
          id: 3758320,
          known_for_department: 'Acting',
          name: 'Lee Doo-seok',
          original_name: 'Lee Doo-seok',
          popularity: 5.879,
          profile_path: '/cQD0FqioziCBJE7KZC3KGmrO6xg.jpg',
        },
        {
          character: 'Girl in a leopard bodypaint',
          credit_id: '6466c001d1857201207fdfb0',
          order: 555,
          adult: false,
          gender: 1,
          id: 2965848,
          known_for_department: 'Acting',
          name: 'Carla Fernanda Avila Escobedo',
          original_name: 'Carla Fernanda Avila Escobedo',
          popularity: 4.328,
          profile_path: '/51UQ3aXayY14tWIR1WP0bPBFbnk.jpg',
        },
      ],
    },
    {
      air_date: '2021-09-17',
      episode_number: 8,
      episode_type: 'standard',
      id: 3146774,
      name: 'O líder',
      overview:
        'Antes da última rodada, a desconfiança e a aversão dominam os finalistas. Jun-ho foge, determinado a expor os segredos sujos do jogo.',
      production_code: '',
      runtime: 33,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/lOgFVmykN9qlpAoiBSIV2lu7XCS.jpg',
      vote_average: 8.168,
      vote_count: 107,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Front Man / Hwang In-ho',
          credit_id: '648e484726346200ae1bc82a',
          order: 1,
          adult: false,
          gender: 2,
          id: 25002,
          known_for_department: 'Acting',
          name: '이병헌',
          original_name: '이병헌',
          popularity: 81.734,
          profile_path: '/pY4pwYO8qwtzvuzpzRczDACDiVA.jpg',
        },
      ],
    },
    {
      air_date: '2021-09-17',
      episode_number: 9,
      episode_type: 'finale',
      id: 3222798,
      name: 'Um dia de sorte',
      overview:
        'A rodada final envolve mais um teste cruel. Mas, desta vez, o resultado depende de apenas um jogador. O criador do jogo se revela.',
      production_code: '',
      runtime: 56,
      season_number: 1,
      show_id: 93405,
      still_path:
        'https://image.tmdb.org/t/p/w400/sKeQbHeEUQLyoSdopa0QXm604cz.jpg',
      vote_average: 7.755,
      vote_count: 110,
      crew: [
        {
          job: 'Writer',
          department: 'Writing',
          credit_id: '62a62d1b7e12f02ff65fff0b',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
        {
          job: 'Director',
          department: 'Directing',
          credit_id: '62a62d2385005d4c07bde35f',
          adult: false,
          gender: 2,
          id: 1294471,
          known_for_department: 'Directing',
          name: '황동혁',
          original_name: '황동혁',
          popularity: 12.67,
          profile_path: '/xyr3b04ayyJtA5ZN3L0Af10WKIR.jpg',
        },
      ],
      guest_stars: [
        {
          character: 'Front Man / Hwang In-ho',
          credit_id: '648e484726346200ae1bc82a',
          order: 1,
          adult: false,
          gender: 2,
          id: 25002,
          known_for_department: 'Acting',
          name: '이병헌',
          original_name: '이병헌',
          popularity: 81.734,
          profile_path: '/pY4pwYO8qwtzvuzpzRczDACDiVA.jpg',
        },
        {
          character: "Sang-woo's mother",
          credit_id: '614f3360c3514c002648f1d0',
          order: 18,
          adult: false,
          gender: 1,
          id: 1661283,
          known_for_department: 'Acting',
          name: '박혜진',
          original_name: '박혜진',
          popularity: 5.316,
          profile_path: '/5cM51cww0P6CVNCRt3BQrGERBfc.jpg',
        },
        {
          character: "Gi-hoon's mother",
          credit_id: '614adf33b0422800438203b9',
          order: 501,
          adult: false,
          gender: 1,
          id: 141153,
          known_for_department: 'Acting',
          name: '김영옥',
          original_name: '김영옥',
          popularity: 10.739,
          profile_path: '/vBk5QGcAFl8rlbkOoV898pa5GAi.jpg',
        },
        {
          character: 'VIP 4',
          credit_id: '614df541fb8346004333d34a',
          order: 523,
          adult: false,
          gender: 2,
          id: 94381,
          known_for_department: 'Acting',
          name: 'Geoffrey Giuliano',
          original_name: 'Geoffrey Giuliano',
          popularity: 13.51,
          profile_path: '/7qHL8KoQkJXtesvmB4mYITh71p2.jpg',
        },
        {
          character: 'VIP 2',
          credit_id: '614df623fb834600611f86bb',
          order: 524,
          adult: false,
          gender: 2,
          id: 3246187,
          known_for_department: 'Acting',
          name: 'Daniel C. Kennedy',
          original_name: 'Daniel C. Kennedy',
          popularity: 23.504,
          profile_path: '/xbLvXLtFZgoxiP6C7k6yB5IWVdk.jpg',
        },
        {
          character: 'VIP 1',
          credit_id: '614df72f2d8ef3002a96fed6',
          order: 525,
          adult: false,
          gender: 2,
          id: 2965857,
          known_for_department: 'Acting',
          name: 'John D. Michaels',
          original_name: 'John D. Michaels',
          popularity: 15.441,
          profile_path: '/1qFYRTG47z6Orgot2G9CcEwL86I.jpg',
        },
        {
          character: 'Flower seller',
          credit_id: '615022f4aaf8970063555023',
          order: 526,
          adult: false,
          gender: 1,
          id: 1099795,
          known_for_department: 'Acting',
          name: '손영순',
          original_name: '손영순',
          popularity: 4.128,
          profile_path: '/yp03B9loF1IfHM0fmsxtomyn8pC.jpg',
        },
        {
          character: 'Banker',
          credit_id: '61502306fb834600433888fd',
          order: 527,
          adult: false,
          gender: 2,
          id: 80985,
          known_for_department: 'Acting',
          name: '이정헌',
          original_name: '이정헌',
          popularity: 2.157,
          profile_path: '/hpEB2cDsZXjdmfwrDVSspQBnWve.jpg',
        },
        {
          character: "Sae-byeok's brother",
          credit_id: '61502340a5d849008df7a3cd',
          order: 528,
          adult: false,
          gender: 2,
          id: 2053103,
          known_for_department: 'Acting',
          name: 'Park Si-wan',
          original_name: 'Park Si-wan',
          popularity: 5.598,
          profile_path: '/7M0Oo7oZOmlYeNelNsP0fy5CCUx.jpg',
        },
        {
          character: 'Hair Stylist',
          credit_id: '6466bfa8d1857200e5a30e4e',
          order: 554,
          adult: false,
          gender: 1,
          id: 3977924,
          known_for_department: 'Acting',
          name: '김민체',
          original_name: '김민체',
          popularity: 1.286,
          profile_path: '/xjOKVxUO6lYxBujNDtHEiiRdBcH.jpg',
        },
        {
          character: 'The Recruiter',
          credit_id: '6571b2c7a22d3e00accf157b',
          order: 557,
          adult: false,
          gender: 2,
          id: 150903,
          known_for_department: 'Acting',
          name: 'Gong Yoo',
          original_name: '공유',
          popularity: 93.937,
          profile_path: '/ocGoFb6TrK3uWGXt4WnuibUG1vD.jpg',
        },
      ],
    },
  ],
  name: 'Temporada 1',
  overview:
    'Centenas de jogadores falidos aceitam um estranho convite para um jogo de sobrevivência. Um prêmio milionário aguarda, mas as apostas são altas e mortais.',
  id: 131977,
  poster_path: 'https://image.tmdb.org/t/p/w400/GB68Yvv0HxPHCTVDJFQCNU17fz.jpg',
  season_number: 1,
  vote_average: 8.3,
};
